### ISSUE TITLE
1.5.0Beta2点设置闪退问题

### ISSUE THREAD

**Issue by Agape2077** [feilongfl/Cimoc#252]
版本 1.5.0-beta2
设备 redmi k20 pro Android Q
错误logcat：
`2020-02-24 20:30:09.940 32579-32579/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hiroshi.cimoc, PID: 32579
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri e.e.a.m.a.d()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri e.e.a.m.a.d()' on a null object reference
        at com.hiroshi.cimoc.ui.activity.SettingsActivity.e0(SettingsActivity.java:2)
        at com.hiroshi.cimoc.ui.activity.BaseActivity.onCreate(BaseActivity.java:13)
        at android.app.Activity.performCreate(Activity.java:7824)
        at android.app.Activity.performCreate(Activity.java:7813)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) `

**Comment by feilongfl** [comment]
今天搜了一下，安卓Q的存储变化很大，需要点时间进行适配。

目前采取下面临时方法解决。
```
android:requestLegacyExternalStorage="true"
```

测试版本`v1.5.0-beta3`

闪退问题集中：
#255
